import { DemoBusiness, MedicalCustomData } from '../types';

const medicalData: MedicalCustomData = {
  clinics: [
    {
      name: 'Kewarra Beach Clinic',
      address: 'Shop 7, 2-6 Cottesloe Drive, Kewarra Beach QLD 4879',
      addressUrl: 'https://maps.google.com/?q=Shop+7+2-6+Cottesloe+Drive+Kewarra+Beach+QLD+4879',
      phone: '07 4032 7500',
      fax: '07 4032 7570',
      hours: [
        { days: 'Monday – Friday', time: '8:00am – 5:00pm' },
        { days: 'Saturday', time: '8:30am – 12:00pm' },
        { days: 'Sunday', time: 'Closed' },
      ],
      bookingUrl: 'https://www.hotdoc.com.au/medical-centres/kewarra-beach-QLD-4879/beaches-family-practice-kewarra-beach/doctors',
    },
    {
      name: 'Trinity Beach Clinic',
      address: '1 Rabaul Street, Trinity Beach QLD 4879',
      addressUrl: 'https://maps.google.com/?q=1+Rabaul+Street+Trinity+Beach+QLD+4879',
      phone: '07 4032 7575',
      fax: '07 4057 6041',
      hours: [
        { days: 'Monday – Friday', time: '8:00am – 5:00pm' },
        { days: 'Saturday', time: '9:00am – 12:00pm' },
        { days: 'Sunday', time: 'Closed' },
      ],
      bookingUrl: 'https://www.hotdoc.com.au/medical-centres/trinity-beach-QLD-4879/beaches-family-practice-trinity-beach/doctors',
    },
  ],
  doctors: [
    {
      name: 'Dr Vivian Matthews',
      qualifications: 'FRACGP, MBBS, FRANZCOG',
      interests: ['Skin Cancer Checks & Treatment', 'Women\'s Health', 'Pregnancy Care'],
      location: 'Kewarra Beach',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Screenshot%20Viv%202.png?itok=kNkRPRRm',
      imageAlt: 'Dr Vivian Matthews, founding GP at Beaches Family Practice Kewarra Beach',
      bio: 'Practice founder since 2006. University of Melbourne graduate with over 25 years of clinical experience.',
    },
    {
      name: 'Dr Nora Duffield',
      qualifications: 'MBChB, FRACGP, FRCGPN',
      interests: ['Nutrition', 'Women\'s Health', 'Diabetes Management'],
      location: 'Trinity Beach',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Beaches%202014-11-24-752.jpg?itok=pOMY4dvy',
      imageAlt: 'Dr Nora Duffield, experienced GP at Beaches Family Practice Trinity Beach',
      bio: 'With the practice since 2002. Brings decades of international experience from Zimbabwe and New Zealand.',
    },
    {
      name: 'Dr Louise Bourke',
      qualifications: 'BSc(Hons), BMBS, FRACGP',
      interests: ['Chronic Disease Management', 'Women\'s Health', 'IUD & Implanon'],
      location: 'Both Clinics',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Louise.jpg?itok=xVCccmqR',
      imageAlt: 'Dr Louise Bourke, GP specialising in chronic disease and women\'s health',
      bio: 'Flinders University graduate with extensive experience in Aboriginal and Torres Strait Islander health.',
    },
    {
      name: 'Dr Patricia Ogilvie',
      qualifications: 'FRACGP, MBChB, MRCGP',
      interests: ['Family Medicine', 'Women\'s Health', 'Mental Health'],
      location: 'Both Clinics',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Beaches%202014-11-24-343.jpg?itok=r6YmhwzE',
      imageAlt: 'Dr Patricia Ogilvie, family GP with dermoscopy expertise',
      bio: 'University of Liverpool trained with qualifications in obstetrics, family planning, and dermoscopy.',
    },
    {
      name: 'Dr Katherine Johnson',
      qualifications: 'FRACGP, MBBS',
      interests: ['Women\'s Health', 'Contraception', 'IUD Insertion'],
      location: 'Both Clinics',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/KJ%203.jpg?itok=Bey87fo7',
      imageAlt: 'Dr Katherine Johnson, GP specialising in women\'s health and contraception',
      bio: 'London graduate (1992) with extensive remote and rural training across Western Australia and Queensland.',
    },
    {
      name: 'Dr Richard Thambyah',
      qualifications: 'FRACGP, MBBS, MPH',
      interests: ['General Medicine', 'Chronic Disease Management', 'Public Health'],
      location: 'Both Clinics',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Beaches%202014-11-24-357.jpg?itok=cGlw6gca',
      imageAlt: 'Dr Richard Thambyah, GP with public health expertise',
      bio: 'Sydney trained with a Master of Public Health. Broad experience in general medicine and chronic disease care.',
    },
    {
      name: 'Dr Emma Doyle',
      qualifications: 'MBBS',
      interests: ['Women\'s Health', 'Mental Health', 'Chronic Disease'],
      location: 'Both Clinics',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Screenshot%20EMMA_0.png?itok=A0IhVEZV',
      imageAlt: 'Dr Emma Doyle, GP with interest in women\'s and mental health',
      bio: 'James Cook University graduate (2020) with IUD insertion qualification and a passion for holistic patient care.',
    },
    {
      name: 'Dr Marlee Paterson',
      qualifications: 'MB DM',
      interests: ['Chronic Disease', 'Preventative Health', 'Skin Cancer'],
      location: 'Trinity Beach',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Screenshot%202026-01-19%20141208.png?itok=64L9CpHe',
      imageAlt: 'Dr Marlee Paterson, GP at Trinity Beach clinic specialising in skin cancer',
      bio: 'Born and raised in Far North Queensland. Passionate about preventative care and skin cancer detection.',
    },
    {
      name: 'Dr Pietro Ridolfi',
      qualifications: 'MBBS',
      interests: ['Paediatrics', 'Men\'s Health', 'Emergency Medicine'],
      location: 'Kewarra Beach',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Pietro_0.jpg?itok=4UEGxhAu',
      imageAlt: 'Dr Pietro Ridolfi, GP at Kewarra Beach with paediatrics and men\'s health focus',
      bio: 'Italian-trained doctor with international experience in the Solomon Islands, New Zealand, and Cairns Emergency Department.',
    },
    {
      name: 'Dr Hamish Albany',
      qualifications: 'MBBS',
      interests: ['Preventative Medicine', 'Paediatrics', 'Sports Medicine'],
      location: 'Kewarra Beach',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/1000032134_0.jpg?itok=JKmK_GyS',
      imageAlt: 'Dr Hamish Albany, GP at Kewarra Beach specialising in sports and preventative medicine',
      bio: 'UNSW graduate (2020) with emergency medicine background. Interest in men\'s health and musculoskeletal conditions.',
    },
    {
      name: 'Dr Brendan Griessel',
      qualifications: 'MBBS',
      interests: ['Men\'s Health', 'Family Medicine', 'Paediatrics'],
      location: 'Both Clinics',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/Screenshot%20Brendan_0.png?itok=b1Wlb2XF',
      imageAlt: 'Dr Brendan Griessel, FNQ native GP specialising in men\'s health and family medicine',
      bio: 'Far North Queensland native with expertise in men\'s health, family medicine, and migraine management.',
    },
    {
      name: 'Dr David Tran',
      qualifications: 'MBBS',
      interests: ['Preventative Medicine', 'General Practice'],
      location: 'Both Clinics',
      acceptingNewPatients: true,
      imageUrl: 'https://www.beachesfamilypractice.com.au/sites/default/files/styles/medium/public/img/doctor/20220216_142910%20%284%29.jpg?itok=9cFPSnMd',
      imageAlt: 'Dr David Tran, James Cook University graduate GP focused on preventative medicine',
      bio: 'James Cook University graduate with hospital experience. Committed to preventative medicine and community health.',
    },
  ],
  onboardingSteps: [
    {
      step: '01',
      title: 'Book Online or Call',
      description: 'Choose your preferred clinic and book via HotDoc or call us directly. Same-day appointments often available.',
      icon: 'CalendarCheck',
    },
    {
      step: '02',
      title: 'Complete Your Details',
      description: 'Fill in the new patient form online or arrive 10 minutes early. Bring your Medicare card and any referral letters.',
      icon: 'ClipboardList',
    },
    {
      step: '03',
      title: 'See Your Doctor',
      description: 'Meet your GP for a thorough initial consultation. We\'ll create a personalised care plan together.',
      icon: 'Stethoscope',
    },
  ],
  accreditations: [
    'AGPAL Accredited Practice',
    'RACGP Standards',
    'Australian Immunisation Provider',
    'Accredited Skin Cancer Clinic',
  ],
  bookingUrl: 'https://www.hotdoc.com.au/medical-centres/kewarra-beach-QLD-4879/beaches-family-practice-kewarra-beach/doctors',
  feeStandard: '$92',
  feeExtended: '$160',
  bulkBillingNote: 'Children under 16 bulk billed. Private billing for all other consultations.',
};

export const beachesfp: DemoBusiness = {
  name: 'Beaches Family Practice',
  tagline: 'Healthcare for the Whole Family — Kewarra Beach & Trinity Beach',
  description:
    'Beaches Family Practice has been caring for families across the Northern Beaches of Cairns since 2006. With clinics in Kewarra Beach and Trinity Beach, our experienced team of GPs provides comprehensive family healthcare in a warm, coastal setting.',
  phone: '07 4032 7500',
  phoneAlt: '07 4032 7575',
  email: 'reception@beachesfamilypractice.com.au',
  address: 'Shop 7, 2-6 Cottesloe Drive, Kewarra Beach QLD 4879',
  logoUrl: 'https://www.beachesfamilypractice.com.au/sites/all/themes/beachesfamilypractice/assets/img/beaches-family-practice-retina.png',
  logoWhiteUrl: 'https://www.beachesfamilypractice.com.au/sites/all/themes/beachesfamilypractice/assets/img/beaches-family-practice-retina.png',
  primaryColor: '#00b2ef',
  primaryColorDark: '#2b4b59',
  accentColor: '#f58825',
  heroTitle: 'Your Family\'s Health,',
  heroHighlight: 'Our Community\'s Care',
  heroSubtitle:
    'Two convenient coastal clinics. One trusted team. Comprehensive family healthcare on Cairns\' beautiful Northern Beaches since 2006.',
  ctaText: 'Book Online Now',
  services: [
    {
      icon: 'Sun',
      title: 'Skin Cancer Checks',
      description: 'Full skin cancer screening, dermoscopy, cryotherapy, biopsy, and surgical excision by specially trained doctors.',
    },
    {
      icon: 'Heart',
      title: 'Women\'s & Men\'s Health',
      description: 'Comprehensive gender-specific care including contraception, IUD insertion, cervical screening, prostate health, and hormone management.',
    },
    {
      icon: 'Syringe',
      title: 'Immunisations',
      description: 'Full childhood vaccination program, adult flu and pneumonia vaccines, travel immunisations with personalised schedules.',
    },
    {
      icon: 'Activity',
      title: 'Chronic Disease Management',
      description: 'Ongoing care for diabetes, heart disease, asthma, and more. Medicare-funded allied health access through EPC plans.',
    },
    {
      icon: 'Baby',
      title: 'Children\'s Health',
      description: 'Full family care from newborns to teens. Health screening, immunisation, and emergency care. Under 16s bulk billed.',
    },
    {
      icon: 'Stethoscope',
      title: 'Pregnancy & Antenatal',
      description: 'Complete antenatal care with shared hospital arrangements. Experienced GPs with obstetric qualifications.',
    },
  ],
  stats: [
    { value: '2006', label: 'Established' },
    { value: '2', label: 'Coastal Clinics' },
    { value: '12', label: 'Experienced GPs', suffix: '+' },
    { value: '18', label: 'Years of Care', suffix: '+' },
  ],
  whyChooseUs: [
    {
      icon: 'Users',
      title: 'Whole Family Care',
      description: 'From newborns to grandparents, our team provides continuous care across every stage of life.',
    },
    {
      icon: 'MapPin',
      title: 'Two Convenient Locations',
      description: 'Clinics at both Kewarra Beach and Trinity Beach for easy access across the Northern Beaches.',
    },
    {
      icon: 'ShieldCheck',
      title: 'Fully Accredited',
      description: 'AGPAL accredited and meeting RACGP standards. Your safety and quality of care is our priority.',
    },
    {
      icon: 'Clock',
      title: 'After Hours Available',
      description: 'After-hours doctor access for registered patients when you need care outside regular hours.',
    },
  ],
  testimonials: [
    {
      quote: 'We\'ve been coming to Beaches Family Practice since our kids were born. The doctors are wonderful — they know our whole family by name. It feels like a community, not just a clinic.',
      author: 'Michelle R.',
      role: 'Kewarra Beach Local',
      rating: 5,
    },
    {
      quote: 'After moving to Trinity Beach, finding a good GP was my top priority. Dr Duffield and the team have been absolutely fantastic. The online booking makes it so easy.',
      author: 'Paul S.',
      role: 'Trinity Beach Resident',
      rating: 5,
    },
    {
      quote: 'The skin cancer check was thorough and professional. Living in North Queensland, it\'s reassuring to have a clinic that takes skin health so seriously. Highly recommend.',
      author: 'Karen W.',
      role: 'Patient since 2015',
      rating: 5,
    },
  ],
  serviceAreas: [
    'Kewarra Beach', 'Trinity Beach', 'Trinity Park', 'Palm Cove',
    'Clifton Beach', 'Smithfield', 'Holloways Beach', 'Yorkeys Knob', 'Cairns Northern Beaches',
  ],
  certifications: [
    'AGPAL Accredited General Practice',
    'RACGP Standards Compliant',
    'Australian Immunisation Provider',
    'Accredited Skin Cancer Clinic',
  ],
  template: 'medical',
  navLinks: [
    { label: 'Our Clinics', href: '#clinics' },
    { label: 'Services', href: '#services' },
    { label: 'Our Doctors', href: '#doctors' },
    { label: 'New Patients', href: '#new-patients' },
    { label: 'Book Now', href: '#book' },
  ],
  custom: medicalData,
};
