import { DemoBusiness } from '../types';

export const sailstructures: DemoBusiness = {
  name: 'Sail Structures',
  tagline: 'Award-Winning Architectural Shade Solutions Since 1988',
  description:
    'Sail Structures is a Cairns-based, multi-award-winning designer-builder specialising in high-quality architectural shade sails, tensile membrane fabric structures, and hard roof shelters. With over 30 years of industry experience, we manufacture from a modern sail loft using cutting-edge technology.',
  phone: '1300 361 880',
  phoneAlt: '07 4035 5540',
  email: 'admin@sailstructures.com.au',
  address: '14 Doyle Street, Bungalow, Cairns QLD 4870',
  logoUrl: 'https://www.sailstructures.com.au/wp-content/uploads/2017/07/sail-structures-logo.png',
  logoWhiteUrl: 'https://www.sailstructures.com.au/wp-content/uploads/2017/08/sail-structures-logo-white.png',
  primaryColor: '#FFB600',
  primaryColorDark: '#1B273D',
  accentColor: '#E8A000',
  heroImage: 'https://www.sailstructures.com.au/wp-content/uploads/2022/07/ReefMagic-1024x682.jpg',
  heroTitle: 'Structures of',
  heroHighlight: 'Excellence',
  heroSubtitle:
    'Multi-award-winning designers and builders of architectural shade sails, tensile membranes, and hard roof shelters. Proudly serving Australia from Cairns since 1988.',
  ctaText: 'Get a Free Quote',
  services: [
    {
      icon: 'Sun',
      title: 'Shade Sails',
      id: 'shade-sails',
      description: 'Stylish, colourful architectural shade sails designed and manufactured for UV and rain protection across commercial, residential, and community spaces.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2021/10/IMG_1866-1024x768.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2021/10/IMG_1866-1024x768.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2020/03/e-1024x768.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2019/08/IMG_8324-1024x1024.jpg',
      ],
      detailedDescription: 'Sail Structures designs, manufactures, and installs architectural shade sails from our purpose-built sail loft in Cairns. Using cutting-edge CAD software and precision cutting equipment, every shade sail is custom-made to suit the site, the aesthetic, and the engineering requirements. Our shade sails provide superior UV protection rated up to 98% UVR block, with options for both waterproof and breathable fabrics. Available in a wide range of colours, shapes, and configurations, our shade sails transform outdoor spaces while protecting people from Australia\'s harsh sun.',
      fabricInfo: 'We use premium shade cloth fabrics including Commercial 95, Rainbow Z16, and Monotec 370 from leading manufacturers. These fabrics are UV-stabilised, fire-retardant rated, and backed by up to 15-year manufacturer warranties. A full range of colours is available to complement any architectural palette.',
      applications: [
        'Schools and childcare centres',
        'Playgrounds and recreation areas',
        'Swimming pools and aquatic centres',
        'Commercial and retail spaces',
        'Hospitality venues and outdoor dining',
        'Residential patios and carports',
      ],
      advantages: [
        'Up to 98% UV radiation block',
        'Custom-designed and manufactured in Cairns',
        'Engineered to Australian wind loading standards',
        'Wide range of colours, shapes, and configurations',
        'Waterproof and breathable fabric options',
        'Up to 15-year fabric manufacturer warranty',
      ],
    },
    {
      icon: 'Layers',
      title: 'Tensile Membranes',
      id: 'tensile-membranes',
      description: 'Ideal for large span roofs and lightweight curved structures. Engineered tensile membrane solutions for striking architectural outcomes.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2017/08/watkins-martin-munro-conservatory-sail-structures-2-1024x681.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2017/08/watkins-martin-munro-conservatory-sail-structures-2-1024x681.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2017/08/Cairns-Airport-2-Award-555-x-416.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2017/08/watkins-martin-munro-conservatory-sail-structures-11.jpg',
      ],
      detailedDescription: 'Tensile membrane structures are lightweight, high-strength fabric structures that achieve their stability through pre-stressed tension rather than compression. Sail Structures specialises in the design and construction of tensile membrane roofs, canopies, and facades that deliver striking architectural outcomes while spanning large areas without internal columns. Our tensile membrane projects include award-winning installations such as the Cairns Airport beer garden canopy and the Watkins Martin Munro Conservatory. We work with world-leading membrane suppliers including Mehler Texnologies and Serge Ferrari to deliver structures that combine beauty with engineering excellence.',
      fabricInfo: 'We supply and install membranes from Mehler Texnologies (FR700, FR900 series) and Serge Ferrari. These PTFE-coated and PVC-coated fabrics offer exceptional durability, self-cleaning properties, and lifespan exceeding 20 years. Available in translucent and opaque options to control light transmission.',
      applications: [
        'Airport terminals and transport hubs',
        'Sporting venues and grandstands',
        'Shopping centre atriums and walkways',
        'Hotel and resort covered areas',
        'Public plazas and civic spaces',
        'Conservatories and botanical gardens',
      ],
      advantages: [
        'Large spans with no internal columns',
        'Lightweight — reduced structural steel requirements',
        'Striking curved and organic architectural forms',
        'Translucent options for natural daylighting',
        'Self-cleaning PTFE and PVC fabric options',
        'Award-winning design and construction capability',
        'Engineered for cyclonic wind regions',
        '20+ year fabric lifespan',
      ],
    },
    {
      icon: 'Umbrella',
      title: 'Skyspan Umbrellas',
      id: 'skyspan-umbrellas',
      description: 'Exclusive supplier of Skyspan commercial umbrellas to Far North Queensland. Premium protection from harsh sun and rain for hospitality and public spaces.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2021/10/IMG20211014121612-1024x768.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2021/10/IMG20211014121612-1024x768.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2017/09/Skyspan-Twin-Vista-1024-x-681-1024x681.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2066-1024x768.jpg',
      ],
      detailedDescription: 'Sail Structures is the exclusive supplier and installer of Skyspan commercial umbrellas in Far North Queensland. Skyspan umbrellas are Australian-engineered, architecturally designed umbrella systems built for commercial and public environments. The range includes centre-post, cantilever, and the innovative Twin Vista double-cantilever models. Skyspan umbrellas are rated for wind speeds up to 118 km/h (when closed), feature marine-grade hardware, and come with a comprehensive manufacturer warranty. They are the premium choice for schools, hospitality venues, resorts, and public spaces requiring reliable, retractable shade.',
      applications: [
        'Hospitality venues and outdoor dining',
        'Schools and university campuses',
        'Resort pool areas and recreation spaces',
        'Shopping centres and retail precincts',
        'Council parks and public spaces',
        'Sporting venue spectator areas',
      ],
      advantages: [
        'Retractable — close during severe weather',
        'Cantilever design — no centre pole obstruction',
        'Wind rated up to 118 km/h (closed position)',
        'Marine-grade stainless steel hardware',
        'Over 30m² coverage per Twin Vista unit',
        'Custom post padding available for schools',
        'Comprehensive manufacturer warranty',
      ],
    },
    {
      icon: 'Building2',
      title: 'Hard Roof Shelters',
      id: 'hard-roof-shelters',
      description: 'Engineered hard roof shelter structures built to withstand long exposure to harsh tropical environments. Durable, low-maintenance solutions.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2017/08/Rockhampton-Special-School-300m2-Hard-Roof-Playground-Shelter-and-CBSR-Softfall-14_7_2017-1024-x-681-1024x681.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2017/08/Rockhampton-Special-School-300m2-Hard-Roof-Playground-Shelter-and-CBSR-Softfall-14_7_2017-1024-x-681-1024x681.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2020/09/a2-1024x768.jpeg',
        'https://www.sailstructures.com.au/wp-content/uploads/2020/04/image-10-1024x768.jpg',
      ],
      detailedDescription: 'Sail Structures designs and builds engineered hard roof shelter structures for schools, councils, and community organisations across Queensland. Our hard roof shelters are built to withstand the harshest tropical environments — from cyclonic coastal regions to remote inland communities. As a DETE (Department of Education) preferred supplier, we have extensive experience delivering playground shelters, covered outdoor learning areas (COLAs), and community shelters that meet strict government specifications. Every structure is engineered to the relevant wind region and site-specific conditions.',
      credential: 'DETE (Department of Education) Preferred Supplier',
      applications: [
        'School playground shelters and COLAs',
        'Community recreation area shelters',
        'Remote and Indigenous community structures',
        'Council park shelters and picnic areas',
        'Splash park and aquatic facility shelters',
      ],
      advantages: [
        'Engineered for cyclonic wind regions',
        'Low maintenance — no fabric replacement required',
        'Pre-fabricated for efficient remote delivery',
        'Corrosion-resistant hardware and coatings',
        'Clear-span designs with no internal columns',
        'CBSR softfall surfacing integration available',
      ],
    },
    {
      icon: 'Tent',
      title: 'Eco-Tents & Glamping',
      id: 'eco-tents-glamping',
      description: 'Environmentally sustainable glamping accommodation and safari-style tents. Perfect for tourism operators and eco-resorts.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2019/08/IMG_5221-1-1024x1024.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2019/08/IMG_5221-1-1024x1024.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2017/08/ECO-TENTS-555-x-416.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2022/10/DSC_0740.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2022/10/DSC_0825.jpg',
      ],
      detailedDescription: 'Sail Structures designs and manufactures environmentally sustainable eco-tent and glamping accommodation structures for the tourism and hospitality industry. Our safari-style luxury tents feature three-layer insulated roofing with ventilation spacing for natural climate control, TREX timber composite platforms providing durable and low-maintenance foundations, and fully customisable interiors. Each eco-tent is designed to minimise environmental footprint while delivering a premium guest experience, making them ideal for eco-resorts, caravan parks, and nature-based tourism operations across tropical and regional Australia.',
      applications: [
        'Eco-resorts and nature retreats',
        'Caravan parks and holiday parks',
        'Farm stays and agri-tourism',
        'National park accommodation',
        'Remote tourism operations',
      ],
      advantages: [
        'Three-layer insulated roofing with natural ventilation',
        'TREX timber composite platforms with 25-year warranty',
        'Minimal site preparation and environmental impact',
        'Fully customisable layouts and interiors',
        'Designed for tropical and harsh climates',
        'Rapid deployment — faster than traditional construction',
      ],
    },
    {
      icon: 'Wrench',
      title: 'Asset Management',
      id: 'asset-management',
      description: 'Full life cycle asset management services for shade portfolios. The only pre-qualified Local Buy supplier of Tactical Asset Management Services.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2020/01/IMG_9560.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2020/01/IMG_9560.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2020/01/IMG_8432.jpg',
      ],
      detailedDescription: 'Sail Structures is the only pre-qualified Local Buy supplier of Tactical Asset Management Services (TAMS) for shade and membrane structures across Queensland. Our asset management program provides councils, schools, and facility managers with a comprehensive framework for managing their shade infrastructure portfolio — from initial audit through to scheduled maintenance, repair, replacement planning, and budget forecasting. We manage shade assets across their full lifecycle, ensuring safety compliance, extending asset life, and optimising renewal budgets.',
      credential: 'Pre-qualified Local Buy Supplier — Tactical Asset Management Services',
      applications: [
        'Condition assessment and auditing',
        'Scheduled preventative maintenance programs',
        'Repair and remediation services',
        'Fabric replacement and re-skinning',
        'Steel and hardware inspection and certification',
        'Asset lifecycle and budget forecasting',
        'Compliance reporting and documentation',
        'Emergency storm damage response',
        'Warranty management and tracking',
        'Capital works replacement planning',
      ],
      advantages: [
        'Only pre-qualified Local Buy TAMS supplier',
        'Full lifecycle management from audit to replacement',
        'Proactive maintenance extends asset lifespan',
        'Detailed reporting and compliance documentation',
        'Budget forecasting for capital renewal planning',
        'Single point of contact for entire shade portfolio',
      ],
    },
    {
      icon: 'Sparkles',
      title: 'Cleaning & Maintenance',
      id: 'cleaning-maintenance',
      description: 'Professional cleaning and maintenance services to extend the lifespan of your shade sail and membrane portfolio.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2020/01/IMG_8432.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2020/01/IMG_8432.jpg',
        'https://www.sailstructures.com.au/wp-content/uploads/2020/01/IMG_9560.jpg',
      ],
      detailedDescription: 'Regular cleaning and maintenance is essential to maximise the lifespan and appearance of shade sails and tensile membrane structures, particularly in tropical environments where mould, mildew, and UV degradation accelerate fabric deterioration. Sail Structures offers professional cleaning and maintenance services using manufacturer-approved products and techniques. Our trained technicians inspect hardware, connections, and fabric condition during every clean, identifying potential issues before they become costly repairs. We work closely with fabric manufacturers to ensure all cleaning methods preserve warranty coverage and fabric integrity.',
      fabricInfo: 'We use cleaning products and methods specifically approved by fabric manufacturers including Commercial 95, Monotec, and Mehler Texnologies. Using non-approved cleaning products can void fabric warranties — our technicians are trained in the correct procedures for each fabric type.',
      applications: [
        'Scheduled shade sail cleaning programs',
        'Tensile membrane cleaning and inspection',
        'Mould and mildew treatment',
        'Hardware and connection inspection',
        'Fabric tension re-adjustment',
        'Storm damage assessment and repair',
      ],
      advantages: [
        'Manufacturer-approved cleaning methods',
        'Preserves fabric warranty coverage',
        'Combined cleaning and safety inspection',
        'Extends fabric and structure lifespan',
        'Scheduled programs for councils and schools',
        'Trained technicians with height safety certification',
      ],
    },
    {
      icon: 'Armchair',
      title: 'Street & Park Furniture',
      id: 'street-park-furniture',
      description: 'Quality street and park furniture solutions for councils, parks, and public spaces across Australia.',
      image: 'https://www.sailstructures.com.au/wp-content/uploads/2020/01/20190429_163039-1024x498.jpg',
      images: [
        'https://www.sailstructures.com.au/wp-content/uploads/2020/01/20190429_163039-1024x498.jpg',
      ],
      detailedDescription: 'Sail Structures supplies and installs premium street and park furniture from leading Australian manufacturers. Our range includes "The Northern" collection by SPARK — a robust, architecturally designed furniture range specifically engineered for harsh tropical and coastal environments. From park benches and picnic settings to bollards, bike racks, and bin enclosures, we provide complete outdoor furniture solutions for councils, developers, and facility managers. All products are designed for durability, low maintenance, and compliance with Australian accessibility standards.',
      applications: [
        'Council parks and recreational reserves',
        'Streetscapes and urban renewal projects',
        'Beachfront and foreshore areas',
        'Shopping precincts and town centres',
        'School and university campuses',
        'Resort and tourism facility grounds',
        'Playground and splash park surrounds',
      ],
      advantages: [
        '"The Northern" range engineered for tropical climates',
        'Corrosion-resistant materials and coatings',
        'DDA-compliant accessible designs',
        'Low maintenance and vandal-resistant options',
        'Complete supply and installation service',
        'Coordinated furniture suites for design consistency',
      ],
    },
  ],
  stats: [
    { value: '30', label: 'Years Experience', suffix: '+' },
    { value: '1000', label: 'Projects Delivered', suffix: '+' },
    { value: '6', label: 'Industry Awards' },
    { value: '100', label: 'Australia-Wide', suffix: '%' },
  ],
  whyChooseUs: [
    {
      icon: 'Award',
      title: 'Multi-Award Winning',
      description: 'Recognised at state, national, and international levels for design and construction excellence in lightweight structures.',
    },
    {
      icon: 'Shield',
      title: 'QBCC Licensed',
      description: 'Fully licensed builder (QBCC 15344519) with Master Builders, STA, and LSAA memberships ensuring quality and compliance.',
    },
    {
      icon: 'Factory',
      title: 'In-House Manufacturing',
      description: 'Purpose-built modern sail loft in Cairns using cutting-edge CAD software and quality fabrics for precision manufacturing.',
    },
    {
      icon: 'Compass',
      title: 'Design & Construct',
      description: 'Complete end-to-end service from initial design and engineering through to manufacturing, installation, and ongoing maintenance.',
    },
  ],
  testimonials: [
    {
      quote: 'They were a pleasure to deal with, were highly knowledgeable, turned up on time, and provided a high quality job. I would have no hesitation in recommending Sail Structures.',
      author: 'Ron Bomgaars',
      role: 'ALH Group Ltd (Dan Murphys)',
      rating: 5,
    },
    {
      quote: 'The project management and installation team was extremely professional. The Skyspan umbrellas have transformed our courtyard, creating another regular meeting place for our students.',
      author: 'Greg Bell',
      role: "St Monica's College",
      rating: 5,
    },
    {
      quote: 'Thank you for wonderful design and delivery of what is unquestionably the highlight of the Village and a structural masterpiece.',
      author: 'Michel Maingard',
      role: 'Project Owner',
      rating: 5,
    },
    {
      quote: 'Sail Structures are the only fabricator to consider when manufacturing and installing shade sails in Cairns. Their workmanship is second to none.',
      author: 'Greg Belgrove',
      role: 'Industry Professional',
      rating: 5,
    },
  ],
  gallery: [
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2017/08/watkins-martin-munro-conservatory-sail-structures-2-1024x681.jpg', alt: 'Watkins Martin Munro Conservatory', link: '/demo/sailstructures/projects/martin-munro-conservatory' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2017/09/Tobruk-Flowrider-1024-x-681-1024x681.jpg', alt: 'Tobruk Pool Flowrider', link: '/demo/sailstructures/projects/tobruk-pool-flowrider' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2017/09/TobrukPoolGym-MehlerFR700Nano16xOutlookCrankhandleBlinds-1024-x-681-1024x681.jpg', alt: 'Tobruk Pool Gym Blinds', link: '/demo/sailstructures/projects/tobruk-pool-gym' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2019/08/IMG_8324-1024x1024.jpg', alt: 'AFL Girls Academy Redlynch', link: '/demo/sailstructures/projects/afl-girls-academy' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2021/10/IMG20211014121612-1024x768.jpg', alt: 'Skyspan Umbrella Installation', link: '/demo/sailstructures/projects/skyspan-umbrella-installation' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2020/03/e-1024x768.jpg', alt: 'Mossman Playground Shade Sails', link: '/demo/sailstructures/projects/mossman-playground' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2020/04/image-10-1024x768.jpg', alt: 'Community Shade Structure', link: '/demo/sailstructures/projects/community-shade-structure' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2020/09/a2-1024x768.jpeg', alt: 'Aurukun Splash Park Shelter', link: '/demo/sailstructures/projects/aurukun-splash-park' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2017/08/Cairns-Airport-2-Award-555-x-416.jpg', alt: 'Cairns Airport Beer Garden Canopy', link: '/demo/sailstructures/projects/cairns-airport-beer-garden' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2020/04/v1-1024x768.jpg', alt: 'Vivo Restaurant Palm Cove', link: '/demo/sailstructures/projects/vivo-restaurant-palm-cove' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2066-1024x768.jpg', alt: "St Monica's College Piazza", link: '/demo/sailstructures/projects/st-monicas-piazza' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2017/08/ECO-TENTS-555-x-416.jpg', alt: 'Eco-Tents & Glamping', link: '/demo/sailstructures/projects/eco-tents-glamping' },
    { src: 'https://www.sailstructures.com.au/wp-content/uploads/2022/07/ReefMagic-1024x682.jpg', alt: 'Reef Magic Pontoon', link: '/demo/sailstructures/projects/reef-magic-pontoon' },
  ],
  serviceAreas: [
    'Cairns', 'Far North Queensland', 'Townsville', 'Rockhampton',
    'Brisbane', 'Sydney', 'Melbourne', 'Remote & Regional Australia',
    'Torres Strait', 'Cape York',
  ],
  certifications: [
    'QBCC Licensed Builder (15344519)',
    'Master Builders Association Member',
    'Shade & Tenting Association Member',
    'LSAA Member (Lightweight Structures)',
    'DETE Preferred Supplier',
    'Local Buy Member',
  ],
  template: 'industrial',
  navLinks: [
    { label: 'Products', href: '#services' },
    { label: 'Why Us', href: '#why-us' },
    { label: 'Projects', href: '#gallery' },
    { label: 'Reviews', href: '#testimonials' },
    { label: 'Contact', href: '#contact' },
  ],
  custom: {
    mapEmbedUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3819.2!2d145.7481!3d-16.9356!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6978670501a37b5b%3A0xf84e7eaff2f0c68d!2s14%20Doyle%20St%2C%20Bungalow%20QLD%204870!5e0!3m2!1sen!2sau!4v1',
    projects: [
      {
        id: 'martin-munro-conservatory',
        title: 'Watkins Martin Munro Conservatory',
        category: 'Tensile Membrane',
        client: 'Cairns Regional Council',
        location: 'Cairns, QLD',
        year: '2017',
        description: 'An award-winning tensile membrane installation for the Watkins Martin Munro Conservatory in partnership with Cairns Regional Council. The project involved designing and installing architectural shade structures to enhance growing conditions for light-sensitive plants while providing UV protection for visitors.',
        challenge: 'The conservatory required a structure that would filter sunlight to protect delicate plant species while maintaining an open, airy aesthetic. The design needed to withstand tropical weather conditions including high winds and heavy rainfall.',
        solution: 'Sail Structures designed a series of tensile membrane canopies using high-quality UV-stabilised fabrics. The structures were engineered to provide optimal light filtration while allowing airflow, creating an ideal microclimate for the conservatory\'s botanical collection.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/08/watkins-martin-munro-conservatory-sail-structures-2-1024x681.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2017/08/watkins-martin-munro-conservatory-sail-structures-11.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2017/08/watkins-martin-munro-conservatory-sail-structures-8.jpg',
        ],
        featured: true,
      },
      {
        id: 'tobruk-pool-flowrider',
        title: 'Tobruk Memorial Pool - Flowrider',
        category: 'Shade Sail',
        client: 'Cairns Regional Council',
        location: 'Cairns, QLD',
        year: '2018',
        description: 'A large-scale shade sail installation over the Flowrider attraction at Tobruk Memorial Pool. The project provided critical UV protection for patrons using the popular wave-riding facility while complementing the modern aquatic centre design.',
        challenge: 'The Flowrider generates significant water spray and turbulence, requiring a shade structure that could withstand moisture exposure while providing maximum coverage over the activity area without obstructing sight lines.',
        solution: 'Custom-designed shade sails were engineered with marine-grade fabrics and stainless steel hardware to resist the corrosive aquatic environment. The sail geometry was optimised to provide shade coverage during peak UV hours while allowing natural ventilation.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/09/Tobruk-Flowrider-1024-x-681-1024x681.jpg',
        ],
        featured: true,
      },
      {
        id: 'tobruk-pool-gym',
        title: 'Tobruk Pool Gym - Mehler Blinds',
        category: 'Tensile Membrane',
        client: 'Cairns Regional Council',
        location: 'Cairns, QLD',
        year: '2018',
        description: 'Installation of 16 Mehler FR700 Nano Outlook crank-handle blinds at the Tobruk Pool gymnasium facility. The project transformed the open-air gym space with retractable tensile membrane blinds providing weather protection and climate control.',
        challenge: 'The gym required flexible weather protection that could be deployed during rain or intense sun while maintaining airflow during cooler periods. The system needed to be easily operable by staff and durable in the tropical climate.',
        solution: 'Sail Structures installed Mehler FR700 Nano fabric blinds with a crank-handle mechanism, allowing staff to quickly adjust coverage based on weather conditions. The high-performance fabric provides UV protection while maintaining visibility and airflow.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/09/TobrukPoolGym-MehlerFR700Nano16xOutlookCrankhandleBlinds-1024-x-681-1024x681.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2015/03/tobruk-pool-gym-01.jpg',
        ],
        featured: false,
      },
      {
        id: 'afl-girls-academy',
        title: 'AFL Girls Academy - Redlynch',
        category: 'Shade Sail',
        client: 'AFL Queensland',
        location: 'Redlynch, QLD',
        year: '2019',
        description: 'Design and installation of architectural shade sails for the AFL Girls Academy sporting facility at Redlynch. The project provided essential sun protection for spectators and players across the outdoor training and event areas.',
        challenge: 'The facility needed shade coverage over spectator areas that could withstand high winds common in the Redlynch valley corridor while providing maximum UV protection for athletes and families during training sessions and game days.',
        solution: 'A series of interconnected shade sails were designed in a dynamic configuration that complements the sporting environment. Heavy-duty fixing points and tensioning systems were engineered for the local wind conditions.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2019/08/IMG_8324-1024x1024.jpg',
        ],
        featured: false,
      },
      {
        id: 'skyspan-umbrella-installation',
        title: 'Skyspan Commercial Umbrella Installation',
        category: 'Skyspan Umbrella',
        client: 'Commercial Client',
        location: 'Cairns, QLD',
        year: '2021',
        description: 'Installation of Skyspan Twin Vista commercial umbrellas for a hospitality venue in Cairns. The innovative cantilever design maximised usable outdoor dining space while providing comprehensive weather protection.',
        challenge: 'The client needed a shade solution that could cover a large outdoor seating area without centre poles that would obstruct the layout. The system needed to withstand tropical storms and be easily retractable when not in use.',
        solution: 'Skyspan Twin Vista cantilever umbrellas were selected for their industry-leading wind rating and side-post design. The umbrellas provide over 30 square metres of coverage each with no centre obstruction, transforming the outdoor dining experience.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2021/10/IMG20211014121612-1024x768.jpg',
        ],
        featured: true,
      },
      {
        id: 'mossman-playground',
        title: 'Mossman Playground Shade Sails',
        category: 'Shade Sail',
        client: 'Douglas Shire Council',
        location: 'Mossman, QLD',
        year: '2020',
        description: 'Design, manufacture, and installation of shade sails for the Mossman community playground. The project provided essential UV protection for children and families in one of the region\'s most popular recreational areas.',
        challenge: 'The playground required shade coverage that met strict council safety standards while complementing the colourful playground equipment. The structures needed to be positioned to provide maximum shade during peak afternoon play hours.',
        solution: 'Vibrant, colourful shade sails were custom-designed to complement the playground aesthetic. Engineered to Australian standards with child-safe hardware, the installation provides over 90% UV block during critical sun exposure periods.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2020/03/e-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'community-shade-structure',
        title: 'Community Recreation Shade Structure',
        category: 'Hard Roof Shelter',
        client: 'Local Government',
        location: 'Far North Queensland',
        year: '2020',
        description: 'A durable hard roof shelter structure designed for a community recreation area in Far North Queensland. The project delivered a permanent, low-maintenance shade and weather protection solution built to withstand harsh tropical conditions.',
        challenge: 'Remote community locations present unique logistical challenges including limited access for heavy machinery, extreme weather exposure, and the need for structures requiring minimal ongoing maintenance.',
        solution: 'A pre-fabricated hard roof shelter was designed for efficient transport and assembly in the remote location. The structure uses cyclone-rated materials and corrosion-resistant hardware suitable for the harsh tropical environment.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2020/04/image-10-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'aurukun-splash-park',
        title: 'Aurukun Splash Park Shelter',
        category: 'Hard Roof Shelter',
        client: 'Aurukun Shire Council',
        location: 'Aurukun, QLD',
        year: '2020',
        description: 'Design and construction of shade shelters for the Aurukun community splash park. This remote community project delivered durable, cyclone-rated structures providing shade and shelter for families in one of Australia\'s most remote locations.',
        challenge: 'Aurukun is located on the western coast of Cape York Peninsula, presenting extreme logistical challenges. All materials and equipment required transport over unsealed roads, and the structures needed to withstand cyclone-level wind loads.',
        solution: 'Sail Structures leveraged their extensive remote community experience to deliver pre-engineered shelter structures. The design incorporated cyclone-rated connections and marine-grade materials suited to the harsh coastal environment.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2020/09/a2-1024x768.jpeg',
        ],
        featured: false,
      },
      {
        id: 'architectural-shade-design',
        title: 'Architectural Shade Sail Feature',
        category: 'Shade Sail',
        client: 'Private Client',
        location: 'Cairns Region, QLD',
        year: '2021',
        description: 'A bespoke architectural shade sail designed as both a functional shade solution and a striking visual feature. The project demonstrates Sail Structures\' ability to combine engineering excellence with creative design.',
        challenge: 'The client wanted a shade structure that would serve as an architectural statement piece while providing functional UV protection over an outdoor entertaining area.',
        solution: 'A custom-shaped shade sail was designed using 3D CAD modelling to achieve the desired aesthetic form while ensuring proper fabric tension and water shedding. Premium materials and custom-fabricated steel posts complete the architectural vision.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2021/07/Crop3-1024x681.jpg',
        ],
        featured: false,
      },
      {
        id: 'commercial-shade-installation',
        title: 'Commercial Shade Structure',
        category: 'Shade Sail',
        client: 'Commercial Client',
        location: 'North Queensland',
        year: '2022',
        description: 'A large-scale commercial shade sail installation providing coverage for an outdoor commercial space. The project showcases Sail Structures\' capability in delivering major commercial shade solutions across North Queensland.',
        challenge: 'The commercial space required extensive shade coverage that could be installed with minimal disruption to ongoing business operations while meeting strict building code requirements.',
        solution: 'Sail Structures managed the project from design through installation with careful staging to minimise business disruption. The shade sails were manufactured in-house at the Cairns sail loft ensuring quality control and timely delivery.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2022/07/IMG-2717-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'tafe-thursday-island',
        title: 'TAFE Queensland - Thursday Island',
        category: 'Shade Sail',
        client: 'TAFE Queensland',
        location: 'Thursday Island, Torres Strait',
        year: '2020',
        description: 'Design and installation of shade sails for the TAFE Queensland campus on Thursday Island in the Torres Strait. This remote project required specialist logistics to deliver quality shade solutions to one of Australia\'s most northerly educational facilities.',
        challenge: 'Thursday Island is accessible only by air or sea, requiring all materials, equipment, and personnel to be transported via barge. The extreme tropical climate and remote location demanded materials resistant to salt air corrosion and intense UV exposure.',
        solution: 'Sail Structures drew on decades of remote community project experience to plan logistics meticulously. Marine-grade hardware and UV-stabilised fabrics were selected for maximum longevity. The installation was completed within a tight schedule during a school break period.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2020/10/TAFE-TI-1024x768.jpg',
        ],
        featured: true,
      },
      {
        id: 'rockhampton-special-school',
        title: 'Rockhampton Special School Playground Shelter',
        category: 'Hard Roof Shelter',
        client: 'Department of Education',
        location: 'Rockhampton, QLD',
        year: '2017',
        description: 'A 300m2 hard roof playground shelter with CBSR softfall surfacing for Rockhampton Special School. The project provided an all-weather outdoor play area for students with special needs.',
        challenge: 'The school required a large-span shelter that could accommodate wheelchair access and specialised play equipment while providing full weather protection. The design needed to meet strict accessibility and safety standards for special needs students.',
        solution: 'A pre-engineered hard roof shelter was designed with generous clear-span coverage and no internal columns to maximise accessible play space. CBSR softfall surfacing was integrated for safety, and the structure was engineered for the local wind region.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/08/Rockhampton-Special-School-300m2-Hard-Roof-Playground-Shelter-and-CBSR-Softfall-14_7_2017-1024-x-681-1024x681.jpg',
        ],
        featured: false,
      },
      {
        id: 'pacific-hotel-cairns',
        title: 'Pacific Hotel Cairns - Outdoor Dining',
        category: 'Tensile Membrane',
        client: 'Pacific Hotel Cairns',
        location: 'Cairns, QLD',
        year: '2021',
        description: 'Installation of tensile membrane shade structures for the Pacific Hotel\'s outdoor dining and entertainment areas along the Cairns Esplanade. The project enhanced the hotel\'s alfresco dining experience with elegant architectural shade.',
        challenge: 'The Esplanade location is exposed to strong coastal winds and salt air. The shade structures needed to complement the hotel\'s premium aesthetic while being robust enough for the demanding coastal environment.',
        solution: 'Custom-designed tensile membrane canopies were engineered with coastal-grade materials and a sleek architectural profile. The structures provide rain and UV protection while maintaining the open, tropical ambiance valued by hotel guests.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2021/08/IMG_4640.jpg',
        ],
        featured: false,
      },
      {
        id: 'napranum-splash-park',
        title: 'Napranum Community Splash Park',
        category: 'Hard Roof Shelter',
        client: 'Napranum Aboriginal Shire Council',
        location: 'Napranum, Cape York, QLD',
        year: '2020',
        description: 'Shade shelter structures for the Napranum community splash park on Cape York Peninsula. Part of Sail Structures\' ongoing commitment to delivering quality infrastructure to remote and regional Indigenous communities.',
        challenge: 'Napranum is located near Weipa on Cape York, requiring extensive logistics planning for material transport. The structures needed to withstand extreme tropical weather including cyclones while being vandal-resistant for long-term community use.',
        solution: 'Heavy-duty hard roof shelters were designed with cyclone-rated connections and robust materials. Sail Structures coordinated barge delivery of pre-fabricated components to minimise on-site construction time and community disruption.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2020/11/IMG_1092-e1606265200461-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'blu-marlin-bistro',
        title: 'Blu Marlin Bistro - Outdoor Shade',
        category: 'Shade Sail',
        client: 'Blu Marlin Bistro',
        location: 'Cairns, QLD',
        year: '2019',
        description: 'Architectural shade sails for the popular Blu Marlin Bistro in Cairns, creating comfortable outdoor dining spaces with protection from tropical sun and rain showers.',
        challenge: 'The hospitality venue needed shade that would enhance the dining atmosphere while protecting patrons from sudden tropical rain. The installation had to work within the existing building structure and tight urban space.',
        solution: 'A series of overlapping shade sails were designed to provide complete coverage with effective water run-off. The sails were fitted with waterproof membranes in key areas and tensioned to create an attractive architectural canopy that extends usable dining space year-round.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2019/08/p5.jpg',
        ],
        featured: false,
      },
      {
        id: 'childcare-centre-shade',
        title: 'Childcare Centre Shade Solutions',
        category: 'Shade Sail',
        client: 'Private Childcare Operator',
        location: 'Cairns Region, QLD',
        year: '2020',
        description: 'Custom shade sail installations for childcare centre outdoor play areas, meeting stringent child safety regulations while providing maximum UV protection for young children during outdoor activities.',
        challenge: 'Childcare centres require shade structures that meet specific safety regulations including minimum height requirements, child-safe hardware, and UV block ratings exceeding 90%. The design needed to cover sandpits, play equipment, and outdoor learning areas.',
        solution: 'Sail Structures designed a compliant shade system using high UV-block fabrics rated to Australian/New Zealand standards. All hardware was specified as child-safe with no sharp edges or pinch points, and the sail heights were set to meet regulatory requirements.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2020/01/image-2-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'sail-loft-manufacturing',
        title: 'In-House Sail Loft Manufacturing',
        category: 'Tensile Membrane',
        client: 'Sail Structures',
        location: 'Bungalow, Cairns, QLD',
        year: '2018',
        description: 'A showcase of Sail Structures\' purpose-built manufacturing facility in Bungalow, Cairns. The modern sail loft uses cutting-edge CAD software and precision cutting equipment to manufacture shade sails and tensile membranes to exacting standards.',
        challenge: 'Maintaining consistent quality across diverse project requirements demands precision manufacturing capabilities. Each shade sail and membrane is custom-designed and requires accurate patterning, cutting, and welding to achieve the engineered fabric tensions.',
        solution: 'The Cairns sail loft features computer-aided design and cutting systems that ensure sub-millimetre accuracy in pattern creation. Experienced sailmakers combine traditional skills with modern technology to produce structures that meet the highest quality standards.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/08/Framing1.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2018/02/IMG_3469.jpg',
        ],
        featured: false,
      },
      {
        id: 'cairns-airport-beer-garden',
        title: 'Cairns Airport Beer Garden Canopy',
        category: 'Tensile Membrane',
        client: 'Cairns Airport',
        location: 'Cairns, QLD',
        year: '2011',
        description: 'An award-winning tensile membrane canopy structure for the Cairns Airport beer garden and outdoor dining precinct. The project created an iconic covered outdoor space for travellers and visitors to enjoy.',
        challenge: 'The airport environment required a structure that met strict aviation safety regulations while providing effective shade and rain protection for the outdoor dining area. The design needed to complement the airport\'s modern architecture.',
        solution: 'A striking tensile membrane canopy was designed with sweeping curves that echo the tropical landscape. The structure provides full weather protection while maintaining an open, airy feel that connects diners to the tropical surroundings.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/08/Cairns-Airport-2-Award-555-x-416.jpg',
        ],
        featured: true,
      },
      {
        id: 'vivo-restaurant-palm-cove',
        title: 'Vivo Restaurant - Palm Cove',
        category: 'Skyspan Umbrella',
        client: 'Vivo Restaurant',
        location: 'Palm Cove, QLD',
        year: '2020',
        description: 'Installation of Skyspan commercial umbrellas at Vivo Restaurant in the prestigious Palm Cove dining precinct. The project enhanced the restaurant\'s outdoor dining capacity with premium shade solutions.',
        challenge: 'Palm Cove\'s beachfront location means high wind exposure and salt air corrosion. The shade solution needed to protect diners from tropical sun and sudden rain while maintaining the upscale dining atmosphere.',
        solution: 'Skyspan commercial umbrellas were selected for their superior wind rating and elegant design. The cantilever configuration maximises usable dining space without obstructive centre poles, and marine-grade materials ensure longevity in the coastal environment.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2020/04/v1-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2020/04/v2-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2020/04/v3-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2020/04/v4-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'st-andrews-school-redlynch',
        title: 'St Andrews School - Redlynch',
        category: 'Skyspan Umbrella',
        client: 'St Andrews Catholic College',
        location: 'Redlynch, QLD',
        year: '2021',
        description: 'A comprehensive Skyspan umbrella installation for St Andrews Catholic College in Redlynch, providing shade coverage across multiple outdoor learning and recreation areas for students and staff.',
        challenge: 'The school required versatile shade solutions that could cover large areas while being safe for a school environment. The umbrellas needed to withstand the Redlynch valley wind corridor and provide UV protection meeting education facility standards.',
        solution: 'Multiple Skyspan umbrellas were strategically positioned across the campus to create shaded outdoor classrooms and play areas. The retractable design allows flexibility for school events, and the robust construction handles the local wind conditions.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2021/06/y9.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2021/06/q1-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2021/06/IMG_0951-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2021/06/q3-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'st-monicas-twin-vista',
        title: "St Monica's College - Twin Vista Umbrellas",
        category: 'Skyspan Umbrella',
        client: "St Monica's College",
        location: 'Cairns, QLD',
        year: '2017',
        description: "Installation of Skyspan Twin Vista double cantilever umbrellas at St Monica's College. The innovative twin-arm design provides extended coverage for the school's outdoor gathering areas.",
        challenge: "The college needed large-span shade coverage over student congregation areas without columns that could pose safety risks during active recreation. The solution needed to complement the college's architectural style.",
        solution: "Skyspan Twin Vista double cantilever umbrellas were installed, providing over 60 square metres of shade per unit. The twin-arm design eliminates centre poles while the retractable mechanism allows the umbrellas to be closed during severe weather events.",
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/09/Skyspan-Twin-Vista-1024-x-681-1024x681.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2017/09/Skyspan-Twin-Vista-1024-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'st-monicas-piazza',
        title: "St Monica's College - Piazza",
        category: 'Skyspan Umbrella',
        client: "St Monica's College",
        location: 'Cairns, QLD',
        year: '2022',
        description: "A major Skyspan umbrella installation at the St Monica's College Piazza, featuring a combination of portable and double cantilever umbrellas to create a flexible, shaded outdoor gathering and event space.",
        challenge: "The piazza needed to accommodate diverse activities from daily student use to formal events. The shade system required flexibility to be reconfigured for different layouts while providing comprehensive weather protection year-round.",
        solution: "A mixed fleet of Skyspan portable and double cantilever umbrellas was deployed across the piazza. The portable units provide reconfigurable shade, while the cantilever units offer permanent coverage over key seating areas. The result is a vibrant, usable outdoor space.",
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2066-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2067-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2068-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2062-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'trinity-anglican-school',
        title: 'Trinity Anglican School - Early Learning Centre',
        category: 'Skyspan Umbrella',
        client: 'Trinity Anglican School',
        location: 'Cairns, QLD',
        year: '2022',
        description: 'Custom post pad Skyspan umbrellas installed at Trinity Anglican School\'s Early Learning Centre, providing safe, child-friendly shade for outdoor play and learning areas.',
        challenge: 'The early learning environment required shade structures with enhanced safety features including padded posts to protect young children during active play. Coverage needed to extend over sandpits, play equipment, and outdoor learning zones.',
        solution: 'Skyspan umbrellas fitted with custom post padding were installed to create safe, shaded play areas. The post pads provide impact protection for young children while the umbrellas deliver comprehensive UV protection exceeding regulatory requirements.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2122-1024x768.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG_6505.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/02/IMG-2126-1024x768.jpg',
        ],
        featured: false,
      },
      {
        id: 'cairns-distance-education',
        title: 'Cairns School of Distance Education',
        category: 'Skyspan Umbrella',
        client: 'Cairns School of Distance Education',
        location: 'Cairns, QLD',
        year: '2022',
        description: 'Installation of a 5.0m hexagonal cantilever retractable Skyspan umbrella system at the Cairns School of Distance Education, providing flexible shade coverage for outdoor educational activities.',
        challenge: 'The school needed a shade solution that could be deployed during outdoor classes and retracted when not in use. The hexagonal design needed to cover a circular outdoor learning area efficiently.',
        solution: 'A 5.0m hexagonal cantilever Skyspan umbrella with retractable mechanism was installed, providing over 19 square metres of shade when deployed. The cantilever design keeps the area clear of obstructions while the retractable feature protects the umbrella during severe weather.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2022/06/IMG_7392.jpg',
        ],
        featured: false,
      },
      {
        id: 'eco-tents-glamping',
        title: 'Eco-Tents & Glamping Accommodation',
        category: 'Eco-Tent',
        client: 'Tourism Operators',
        location: 'Queensland',
        year: '2022',
        description: 'Design and manufacture of environmentally sustainable eco-tent and glamping accommodation structures. These safari-style luxury tents feature three-layer insulated roofing, TREX timber composite platforms, and fully customisable interiors for tourism and hospitality operators.',
        challenge: 'Tourism operators needed accommodation solutions that minimise environmental impact while delivering a premium guest experience. The structures needed to withstand tropical weather, resist insect intrusion, and require minimal site preparation.',
        solution: 'Sail Structures developed eco-tent designs featuring three-layer roof construction with ventilation spacing for natural climate control. TREX timber composite platforms provide durable, low-maintenance foundations with commercial and residential warranties. Each tent is fully customisable to suit the operator\'s unique setting.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2017/08/ECO-TENTS-555-x-416.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/10/DSC_0740.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/10/DSC_0825.jpg',
        ],
        featured: true,
      },
      {
        id: 'reef-magic-pontoon',
        title: 'Reef Magic Pontoon',
        category: 'Tensile Membrane',
        client: 'Experience Co. Ltd.',
        location: 'Great Barrier Reef, QLD',
        year: '2022',
        description: 'Design, fabrication, and installation of tensile membranes and shade systems for the state-of-the-art Reef Magic Pontoon — a 1,003m² three-level vessel accommodating 450+ guests on the Great Barrier Reef. Sail Structures delivered 4 tensile membranes (222m²), 2 lifeguard tower membranes (18m²), and 2 shade sails (71m²) using Mehler FR700 Nano and Monotec 370 fabrics.',
        challenge: 'Installing tensile membranes on a floating marine vessel presents unique engineering challenges. The structures needed to withstand open-ocean wind loads, salt spray corrosion, and constant movement, while providing reliable shade and weather protection for hundreds of passengers daily.',
        solution: 'Sail Structures engineered bespoke tensile membrane canopies using marine-grade Mehler FR700 Nano and Monotec 370 fabrics, designed to accommodate the dynamic forces of a floating platform. All hardware was specified in marine-grade stainless steel for maximum corrosion resistance. The project was completed in collaboration with naval architect G.A. Glanville & Co. and builder English Engineering, launching in April 2022.',
        images: [
          'https://www.sailstructures.com.au/wp-content/uploads/2022/07/ReefMagic-1024x682.jpg',
          'https://www.sailstructures.com.au/wp-content/uploads/2022/07/ReefMagic.jpg',
        ],
        featured: true,
      },
    ],
    credentialLogos: [
      { src: 'https://www.sailstructures.com.au/wp-content/uploads/2020/03/MBA_ProudMember_Logo-e1584571075221.jpg', alt: 'Master Builders Association Member' },
      { src: 'https://www.sailstructures.com.au/wp-content/uploads/2023/06/STA-Member.jpg', alt: 'Shade and Tenting Association Member' },
      { src: 'https://www.sailstructures.com.au/wp-content/uploads/2023/06/LSAA-Member.jpg', alt: 'Lightweight Structures Association of Australia Member' },
    ],
    credentialsTitle: 'Our',
    credentialsHighlight: 'Credentials',
    credentialsSubtitle: 'Proudly accredited by leading industry bodies, ensuring the highest standards of quality, safety, and workmanship across every project.',
    heroBadge: 'Award-Winning Shade Solutions Since 1988',
    servicesSubtitle: 'From architectural shade sails to tensile membranes and hard roof shelters, we deliver high-quality lightweight structures built to last.',
    whyUsSubtitle: 'For over 30 years, we\'ve been delivering award-winning shade and shelter solutions across Australia. Our commitment to quality workmanship has made us the industry leader.',
    gallerySubtitle: 'A selection of our award-winning shade sail, tensile membrane, and hard roof shelter projects across Australia.',
    serviceAreasSubtitle: 'From Cairns to capital cities and remote communities, we deliver shade and shelter solutions across the entire country.',
    ctaSubtitle: 'Get a free quote for your shade or shelter project. Our experienced team is ready to help.',
    trustBadges: ['QBCC Licensed', '30+ Years Experience', 'Award Winning'],
    testimonialsHeading: 'Trusted by Clients',
    testimonialsHighlight: 'Across Australia',
    whyUsHeading: 'Quality, Innovation &',
    whyUsHighlight: 'Excellence',
    whyUsTagline: 'You Can Count On',
    serviceAreasHeading: 'Proudly Serving\nAll of Australia',
  },
};
