// services/gemini-image.ts
// Image generation service using Gemini 3 Pro Image Preview

import { GoogleGenAI } from '@google/genai';
import * as fs from 'fs';
import * as path from 'path';
import { ProductConfig } from '../types/article';
import { generateImagePrompt } from '../config/prompts';
import logger from '../utils/logger';

const IMAGE_MODEL = 'gemini-3-pro-image-preview';

export const generateFeaturedImage = async (
  topic: string,
  product: ProductConfig,
  outputPath: string
): Promise<string> => {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is not set');
  }

  logger.step(4, 'Generating featured image with Gemini...');
  logger.keyValue('Model', IMAGE_MODEL);

  const ai = new GoogleGenAI({ apiKey });

  const prompt = generateImagePrompt(topic, product);

  logger.preview('Image Prompt', prompt, 200);

  const response = await ai.models.generateContent({
    model: IMAGE_MODEL,
    contents: prompt,
    config: {
      responseModalities: ['image', 'text'],
      imageSizes: '16:9',
    }
  });

  // Extract image from response parts
  const parts = response.candidates?.[0]?.content?.parts;
  if (!parts || parts.length === 0) {
    throw new Error('No content generated by Gemini');
  }

  // Find the image part
  const imagePart = parts.find((part: any) => part.inlineData?.mimeType?.startsWith('image/'));

  if (!imagePart?.inlineData?.data) {
    throw new Error('No image data in response');
  }

  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Write image to file
  const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');
  fs.writeFileSync(outputPath, imageBuffer);

  logger.success('Featured image generated successfully');
  logger.keyValue('Output', outputPath);

  return outputPath;
};

export const generateImagePreview = (
  topic: string,
  product: ProductConfig
): string => {
  return generateImagePrompt(topic, product);
};
