// services/gemini-image.ts
// Image generation service using Imagen

import { GoogleGenAI } from '@google/genai';
import * as fs from 'fs';
import * as path from 'path';
import { ProductConfig } from '../types/article';
import { generateImagePrompt } from '../config/prompts';
import logger from '../utils/logger';

export const generateFeaturedImage = async (
  topic: string,
  product: ProductConfig,
  outputPath: string
): Promise<string> => {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error('GEMINI_API_KEY environment variable is not set');
  }

  logger.step(4, 'Generating featured image with Imagen...');
  logger.keyValue('Model', 'imagen-4.0-generate-001');

  const ai = new GoogleGenAI({ apiKey });

  const prompt = generateImagePrompt(topic, product);

  logger.preview('Image Prompt', prompt, 200);

  const response = await ai.models.generateImages({
    model: 'imagen-4.0-generate-001',
    prompt: prompt,
    config: {
      numberOfImages: 1,
      aspectRatio: '16:9',
      outputMimeType: 'image/png',
    }
  });

  if (!response.generatedImages || response.generatedImages.length === 0) {
    throw new Error('No images generated by Imagen');
  }

  const image = response.generatedImages[0];

  if (!image.image?.imageBytes) {
    throw new Error('No image data in response');
  }

  // Ensure directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // Write image to file
  const imageBuffer = Buffer.from(image.image.imageBytes, 'base64');
  fs.writeFileSync(outputPath, imageBuffer);

  logger.success('Featured image generated successfully');
  logger.keyValue('Output', outputPath);

  return outputPath;
};

export const generateImagePreview = (
  topic: string,
  product: ProductConfig
): string => {
  return generateImagePrompt(topic, product);
};
